### ISSUE TITLE
Missing prerequisite

### ISSUE THREAD

**Issue by MathTauAthogen** [intermezzio/fake-webcam-video#1]
The README seems to be missing a prerequisite that it might be good to add.

At least on Ubuntu 18.04, modprobe throws the error (if the commands currently in the README are run in a fresh instance),

modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.4.0-42-generic

**Comment by intermezzio** [comment]
To fix this, you'll need to install the v4l2loopback-dkms package on your computer. On Ubuntu, the command is `sudo apt-get install v4l2loopback-dkms`. I will add this installation instruction to the README.
