### ISSUE TITLE
Can't make new webcam

### ISSUE THREAD

**Issue by MathTauAthogen** [intermezzio/fake-webcam-video#2]
Upon running sudo modprobe v4l2loopback video_nr=2, I get the following output:

modprobe: ERROR: could not insert 'v4l2loopback': Bad address

**Comment by intermezzio** [comment]
https://askubuntu.com/questions/1263554/sudo-modprobe-v4l2loopback-modprobe-error-could-not-insert-v4l2loopback-bad suggests installing v4l2loopback from source:
```
sudo apt purge v4l2loopback-dkms
git clone https://github.com/umlaeute/v4l2loopback.git
cd v4l2loopback
make
sudo su
make install
```

**Comment by MathTauAthogen** [comment]
Ok. That worked except I had to run sudo depmod -a right after.
Thanks!
